# Generated by Django 5.1.2 on 2024-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('income', models.IntegerField()),
                ('dob', models.CharField(max_length=8)),
                ('account_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
